spring:
  application:
    name: search-service
  data:
    mongodb:
      uri: ${DATASOURCE_URL}
      database: ${DATASOURCE_DATABASE}
      password: ${DATASOURCE_PASSWORD}
      username: ${DATASOURCE_USERNAME}

server:
  port: 80
  servlet:
    context-path: '/search'